version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install npm dependencies
          command: |
            npm install --save
  
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            docker build -t astha1712/nodejswebapp:latest .
            echo $DOCKER_PASSWORD | docker login -u astha1712 --password-stdin
            docker push astha1712/nodejswebapp:latest

workflows:
  build_and_deploy:
    jobs:
      - build_test
      - build_docker_image
